lang: de_CH
url: https://huby-ch.github.io
title: Huby CH
description: Eine Webseite
github:
  is_project_page: false
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-last-modified-at
